### ISSUE TITLE
Don't compile the source SolarNews

### ISSUE THREAD

**Issue by vadermemo** [hajjiTarik/SolarNews#16]
Hi friend,

  When I clicking to test on device I got the next log on XCode

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTSRWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTInspectorPackagerConnection.o)
  "_OBJC_CLASS_$_RCTReconnectingWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTPackagerConnection.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is something wrong or omitted with your code?

thanks in advance.

**Comment by hajjiTarik** [comment]
Hi,
can you plz try this solution :
Target ->Linking -> other linker Flag and add $(inherited) in other linker flag in both Debug and Release
